use std::fmt::Write as _;
use std::path::Path;

use crate::error::Result;
use crate::metadata::SampleMetadata;
use crate::parser::types::{ModuleStatus, QcResults};
use crate::threshold::{QcLevel, ThresholdConfig};
use crate::ui::tabs::cohort;
use crate::ui::tabs::summary;

/// Render a single, self-contained static HTML report.
///
/// Output is a portable file with embedded CSS and inline SVG charts — no
/// external assets, no JavaScript, suitable for emailing or attaching to a
/// pull request. Layout mirrors the TUI: Summary table, Cohort outlier
/// analysis, then per-tool detail sections.
pub fn write_html(
    path: &Path,
    results: &QcResults,
    thresholds: &ThresholdConfig,
    metadata: Option<&SampleMetadata>,
    active_group_dim: Option<&str>,
) -> Result<()> {
    let mut out = String::with_capacity(64 * 1024);

    out.push_str("<!doctype html>\n");
    out.push_str("<html lang=\"en\">\n<head>\n");
    out.push_str("<meta charset=\"utf-8\">\n");
    out.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
    let title = format!("QCForge report — {}", results.scan_path.display());
    let _ = write!(out, "<title>{}</title>\n", html_escape(&title));
    out.push_str("<style>\n");
    out.push_str(EMBEDDED_CSS);
    out.push_str("\n</style>\n</head>\n<body>\n");

    render_header(&mut out, results, thresholds, metadata, active_group_dim);
    render_summary_section(&mut out, results, thresholds);
    render_cohort_section(&mut out, results, thresholds, metadata, active_group_dim);
    render_samtools_section(&mut out, results, thresholds);
    render_bcftools_section(&mut out, results, thresholds);
    render_fastqc_section(&mut out, results);

    out.push_str("<footer>");
    let _ = write!(
        out,
        "Generated by <strong>QCForge v{}</strong>",
        env!("CARGO_PKG_VERSION")
    );
    out.push_str("</footer>\n</body>\n</html>\n");

    std::fs::write(path, out)?;
    Ok(())
}

fn render_header(
    out: &mut String,
    results: &QcResults,
    thresholds: &ThresholdConfig,
    metadata: Option<&SampleMetadata>,
    active_group_dim: Option<&str>,
) {
    let n_samtools = results.samtools_reports.len();
    let n_bcftools = results.bcftools_reports.len();
    let n_fastqc = results.fastqc_reports.len();

    out.push_str("<header>\n<h1>QCForge Report</h1>\n");
    out.push_str("<dl class=\"meta\">\n");
    let _ = write!(
        out,
        "<dt>Path</dt><dd><code>{}</code></dd>\n",
        html_escape(&results.scan_path.display().to_string())
    );
    let _ = write!(
        out,
        "<dt>Reports</dt><dd>{} samtools, {} bcftools, {} FastQC</dd>\n",
        n_samtools, n_bcftools, n_fastqc
    );
    let _ = write!(
        out,
        "<dt>Thresholds</dt><dd>mapping ≥ {}/{} · dup ≤ {}/{} · err ≤ {}/{} · ts/tv ≥ {}/{} · |gc-50| ≤ {}/{}</dd>\n",
        thresholds.mapping_rate.warn,
        thresholds.mapping_rate.fail,
        thresholds.duplication_rate.warn,
        thresholds.duplication_rate.fail,
        thresholds.error_rate.warn,
        thresholds.error_rate.fail,
        thresholds.ts_tv_ratio.warn,
        thresholds.ts_tv_ratio.fail,
        thresholds.gc_deviation.warn,
        thresholds.gc_deviation.fail,
    );
    if let (Some(md), Some(dim)) = (metadata, active_group_dim) {
        let _ = write!(
            out,
            "<dt>Cohort grouping</dt><dd>by <code>{}</code> ({} dimensions available)</dd>\n",
            html_escape(dim),
            md.dimensions.len()
        );
    }
    out.push_str("</dl>\n</header>\n");
}

fn render_summary_section(out: &mut String, results: &QcResults, thresholds: &ThresholdConfig) {
    out.push_str("<section id=\"summary\">\n<h2>Summary</h2>\n");
    let rows = summary::build_summary_rows(results, thresholds);
    if rows.is_empty() {
        out.push_str("<p class=\"empty\">No QC reports loaded.</p>\n</section>\n");
        return;
    }
    out.push_str("<table class=\"summary\">\n<thead><tr>");
    out.push_str("<th>File</th><th>Tool</th><th>Reads</th><th>Map %</th><th>Dup %</th>");
    out.push_str("<th>Error</th><th>AvgQ</th><th>Vars</th><th>SNPs</th><th>InDels</th>");
    out.push_str("<th>Ts/Tv</th><th>Seqs</th><th>GC %</th><th>P</th><th>W</th><th>F</th>");
    out.push_str("<th>QC</th></tr></thead>\n<tbody>\n");

    for r in &rows {
        out.push_str("<tr>");
        let _ = write!(out, "<td><code>{}</code></td>", html_escape(&r.filename));
        let _ = write!(
            out,
            "<td class=\"tool tool-{}\">{}</td>",
            css_class(&r.tool),
            html_escape(&r.tool)
        );
        td_opt_u64(out, r.reads);
        td_opt_pct(out, r.mapped_pct, |v| {
            level_class(thresholds.mapping_rate.evaluate(v))
        });
        td_opt_pct(out, r.dup_pct, |v| {
            level_class(thresholds.duplication_rate.evaluate(v))
        });
        td_opt_f64(out, r.error_rate, 4, |v| {
            level_class(thresholds.error_rate.evaluate(v))
        });
        td_opt_f64(out, r.avg_quality, 1, |_| "");
        td_opt_u64(out, r.variants);
        td_opt_u64(out, r.snps);
        td_opt_u64(out, r.indels);
        td_opt_f64(out, r.ts_tv, 2, |v| {
            level_class(thresholds.ts_tv_ratio.evaluate(v))
        });
        td_opt_u64(out, r.total_seqs);
        td_opt_f64(out, r.gc_pct, 1, |v| {
            level_class(thresholds.gc_deviation.evaluate((v - 50.0).abs()))
        });
        td_opt_u32(out, r.pass_modules);
        td_opt_u32(out, r.warn_modules);
        td_opt_u32(out, r.fail_modules);
        let qc_class = match r.overall_qc {
            QcLevel::Pass => "pass",
            QcLevel::Warn => "warn",
            QcLevel::Fail => "fail",
        };
        let qc_label = match r.overall_qc {
            QcLevel::Pass => "PASS",
            QcLevel::Warn => "WARN",
            QcLevel::Fail => "FAIL",
        };
        let _ = write!(
            out,
            "<td class=\"qc qc-{}\"><strong>{}</strong></td>",
            qc_class, qc_label
        );
        out.push_str("</tr>\n");
    }
    out.push_str("</tbody>\n</table>\n</section>\n");
}

fn render_cohort_section(
    out: &mut String,
    results: &QcResults,
    thresholds: &ThresholdConfig,
    metadata: Option<&SampleMetadata>,
    active_group_dim: Option<&str>,
) {
    out.push_str("<section id=\"cohort\">\n<h2>Cohort outlier analysis</h2>\n");
    let cohort_data = cohort::build_cohort_data(results, thresholds);
    let rows = cohort::build_cohort_rows(&cohort_data, metadata, active_group_dim);
    let any_qualifies = rows.iter().any(|r| r.stats.is_some());

    if !any_qualifies {
        out.push_str(
            "<p class=\"empty\">Cohort analysis requires ≥5 samples per metric.</p>\n</section>\n",
        );
        return;
    }

    let mut last_metric: Option<cohort::CohortMetric> = None;
    out.push_str("<div class=\"boxplots\">\n");
    for row in &rows {
        if last_metric != Some(row.metric) {
            if last_metric.is_some() {
                out.push_str("</div>\n"); // close metric-group
            }
            let _ = write!(
                out,
                "<div class=\"metric-group\"><h3>{}</h3>\n",
                html_escape(row.metric.label())
            );
            last_metric = Some(row.metric);
        }
        render_boxplot_svg(out, row);
    }
    if last_metric.is_some() {
        out.push_str("</div>\n");
    }
    out.push_str("</div>\n");

    let outliers = cohort::collect_all_outliers(&rows);
    if outliers.is_empty() {
        out.push_str("<p class=\"empty good\">No cohort-relative outliers detected.</p>\n");
    } else {
        let _ = write!(out, "<h3>Outliers ({})</h3>\n", outliers.len());
        out.push_str("<table class=\"outliers\">\n<thead><tr>");
        out.push_str("<th>Sample</th>");
        if active_group_dim.is_some() {
            out.push_str("<th>Group</th>");
        }
        out.push_str(
            "<th>Metric</th><th>Value</th><th>Fence</th><th>Δ</th><th>Side</th><th>Threshold</th>",
        );
        out.push_str("</tr></thead>\n<tbody>\n");
        for o in &outliers {
            out.push_str("<tr>");
            let _ = write!(out, "<td><code>{}</code></td>", html_escape(&o.filename));
            if active_group_dim.is_some() {
                let g = o
                    .group_label
                    .clone()
                    .unwrap_or_else(|| "Ungrouped".to_string());
                let _ = write!(out, "<td>{}</td>", html_escape(&g));
            }
            let _ = write!(out, "<td>{}</td>", html_escape(o.metric.label()));
            let _ = write!(out, "<td>{}</td>", o.metric.format_value(o.value));
            let fence = match o.direction {
                cohort::OutlierDirection::Below => o.value + o.deviation_magnitude,
                cohort::OutlierDirection::Above => o.value - o.deviation_magnitude,
            };
            let _ = write!(out, "<td>{}</td>", o.metric.format_value(fence));
            let _ = write!(
                out,
                "<td>{}</td>",
                o.metric.format_value(o.deviation_magnitude)
            );
            let side = match o.direction {
                cohort::OutlierDirection::Below => "Below",
                cohort::OutlierDirection::Above => "Above",
            };
            let _ = write!(out, "<td>{}</td>", side);
            if o.threshold_fail {
                out.push_str("<td class=\"qc qc-fail\"><strong>FAIL</strong></td>");
            } else {
                out.push_str("<td class=\"qc qc-pass\"><strong>PASS</strong></td>");
            }
            out.push_str("</tr>\n");
        }
        out.push_str("</tbody>\n</table>\n");
    }
    out.push_str("</section>\n");
}

const SVG_W: u32 = 600;
const SVG_H: u32 = 50;
const SVG_PAD: u32 = 70;

fn render_boxplot_svg(out: &mut String, row: &cohort::CohortRow) {
    let label = match &row.group_label {
        Some(g) => format!("[{}]", g),
        None => String::new(),
    };

    let stats = match &row.stats {
        Some(s) => s,
        None => {
            let _ = write!(
                out,
                "<div class=\"boxrow too-small\"><span class=\"glabel\">{}</span>\
                 <span class=\"warn\">n={} — too small (need ≥5)</span></div>\n",
                html_escape(&label),
                row.points.len()
            );
            return;
        }
    };

    let axis_min = stats.min.min(stats.lower_fence);
    let axis_max = stats.max.max(stats.upper_fence);
    let span = (axis_max - axis_min).max(f64::EPSILON);
    let inner_w = SVG_W - 2 * SVG_PAD;
    let to_x = |v: f64| -> f64 {
        let frac = ((v - axis_min) / span).clamp(0.0, 1.0);
        SVG_PAD as f64 + frac * inner_w as f64
    };

    let y_mid = (SVG_H / 2) as f64;
    let box_top = y_mid - 10.0;
    let box_bot = y_mid + 10.0;

    let _ = write!(
        out,
        "<div class=\"boxrow\"><span class=\"glabel\">{}</span>\
         <svg viewBox=\"0 0 {} {}\" xmlns=\"http://www.w3.org/2000/svg\" \
         preserveAspectRatio=\"none\" class=\"boxplot\">",
        html_escape(&label),
        SVG_W,
        SVG_H,
    );

    // axis min/max labels
    let _ = write!(
        out,
        "<text x=\"{}\" y=\"{:.0}\" class=\"axislabel\" text-anchor=\"end\">{}</text>",
        SVG_PAD - 6,
        y_mid + 4.0,
        html_escape(&row.metric.format_value(axis_min)),
    );
    let _ = write!(
        out,
        "<text x=\"{}\" y=\"{:.0}\" class=\"axislabel\" text-anchor=\"start\">{}</text>",
        SVG_W - SVG_PAD + 6,
        y_mid + 4.0,
        html_escape(&row.metric.format_value(axis_max)),
    );

    // whisker line
    let _ = write!(
        out,
        "<line x1=\"{:.1}\" y1=\"{:.0}\" x2=\"{:.1}\" y2=\"{:.0}\" class=\"whisker\"/>",
        to_x(stats.lower_fence),
        y_mid,
        to_x(stats.upper_fence),
        y_mid,
    );
    // fence caps
    for v in [stats.lower_fence, stats.upper_fence] {
        let _ = write!(
            out,
            "<line x1=\"{:.1}\" y1=\"{:.0}\" x2=\"{:.1}\" y2=\"{:.0}\" class=\"fence\"/>",
            to_x(v),
            y_mid - 6.0,
            to_x(v),
            y_mid + 6.0,
        );
    }
    // box
    let q1x = to_x(stats.q1);
    let q3x = to_x(stats.q3);
    let _ = write!(
        out,
        "<rect x=\"{:.1}\" y=\"{:.0}\" width=\"{:.1}\" height=\"{:.0}\" class=\"box\"/>",
        q1x,
        box_top,
        (q3x - q1x).max(0.5),
        box_bot - box_top,
    );
    // median
    let medx = to_x(stats.median);
    let _ = write!(
        out,
        "<line x1=\"{:.1}\" y1=\"{:.0}\" x2=\"{:.1}\" y2=\"{:.0}\" class=\"median\"/>",
        medx, box_top, medx, box_bot,
    );

    // outliers
    for p in &row.points {
        if p.value < stats.lower_fence || p.value > stats.upper_fence {
            let class = if p.threshold_fail {
                "outlier-fail"
            } else {
                "outlier"
            };
            let _ = write!(
                out,
                "<circle cx=\"{:.1}\" cy=\"{:.0}\" r=\"3.5\" class=\"{}\">\
                 <title>{} = {}</title></circle>",
                to_x(p.value),
                y_mid,
                class,
                html_escape(&p.filename),
                row.metric.format_value(p.value),
            );
        }
    }

    out.push_str("</svg></div>\n");
}

fn render_samtools_section(out: &mut String, results: &QcResults, thresholds: &ThresholdConfig) {
    if results.samtools_reports.is_empty() {
        return;
    }
    out.push_str("<section id=\"samtools\">\n<h2>samtools detail</h2>\n");
    for r in &results.samtools_reports {
        let fname = file_basename(&r.source_file);
        let s = &r.summary;
        let mapped = s.mapping_percent();
        let dup = s.duplication_percent();
        let paired = s.properly_paired_percent();
        let _ = write!(
            out,
            "<details><summary><code>{}</code> — {} reads, {:.1}% mapped</summary>\n",
            html_escape(&fname),
            format_number(s.raw_total_sequences),
            mapped,
        );
        out.push_str("<table class=\"detail\"><tbody>\n");
        kv_row(out, "Total reads", &format_number(s.raw_total_sequences));
        kv_row_class(
            out,
            "Mapped",
            &format!("{:.2}% ({})", mapped, format_number(s.reads_mapped)),
            level_class(thresholds.mapping_rate.evaluate(mapped)),
        );
        kv_row_class(
            out,
            "Duplicated",
            &format!("{:.2}% ({})", dup, format_number(s.reads_duplicated)),
            level_class(thresholds.duplication_rate.evaluate(dup)),
        );
        kv_row(
            out,
            "Properly paired",
            &format!(
                "{:.2}% ({})",
                paired,
                format_number(s.reads_properly_paired)
            ),
        );
        kv_row_class(
            out,
            "Error rate",
            &format!("{:.4}", s.error_rate),
            level_class(thresholds.error_rate.evaluate(s.error_rate)),
        );
        kv_row(out, "Average quality", &format!("{:.2}", s.average_quality));
        kv_row(
            out,
            "Insert size avg",
            &format!("{:.1}", s.insert_size_average),
        );
        out.push_str("</tbody></table></details>\n");
    }
    out.push_str("</section>\n");
}

fn render_bcftools_section(out: &mut String, results: &QcResults, thresholds: &ThresholdConfig) {
    if results.bcftools_reports.is_empty() {
        return;
    }
    out.push_str("<section id=\"bcftools\">\n<h2>bcftools detail</h2>\n");
    for r in &results.bcftools_reports {
        let fname = file_basename(&r.source_file);
        let _ = write!(
            out,
            "<details><summary><code>{}</code> — {} variants, Ts/Tv {:.2}</summary>\n",
            html_escape(&fname),
            format_number(r.summary.num_records),
            r.tstv.ts_tv_ratio,
        );
        out.push_str("<table class=\"detail\"><tbody>\n");
        kv_row(out, "Records", &format_number(r.summary.num_records));
        kv_row(out, "SNPs", &format_number(r.summary.num_snps));
        kv_row(out, "InDels", &format_number(r.summary.num_indels));
        kv_row(out, "MNPs", &format_number(r.summary.num_mnps));
        kv_row_class(
            out,
            "Ts/Tv",
            &format!("{:.3}", r.tstv.ts_tv_ratio),
            level_class(thresholds.ts_tv_ratio.evaluate(r.tstv.ts_tv_ratio)),
        );
        kv_row(out, "Ts (transitions)", &format_number(r.tstv.ts));
        kv_row(out, "Tv (transversions)", &format_number(r.tstv.tv));
        out.push_str("</tbody></table></details>\n");
    }
    out.push_str("</section>\n");
}

fn render_fastqc_section(out: &mut String, results: &QcResults) {
    if results.fastqc_reports.is_empty() {
        return;
    }
    out.push_str("<section id=\"fastqc\">\n<h2>FastQC detail</h2>\n");
    for r in &results.fastqc_reports {
        let fname = if r.sample_name.is_empty() {
            file_basename(&r.source_file)
        } else {
            r.sample_name.clone()
        };
        let bs = &r.basic_statistics;
        let _ = write!(
            out,
            "<details><summary><code>{}</code> — {} sequences, GC {:.1}%</summary>\n",
            html_escape(&fname),
            format_number(bs.total_sequences),
            bs.percent_gc,
        );
        out.push_str("<table class=\"detail\"><tbody>\n");
        kv_row(out, "Total sequences", &format_number(bs.total_sequences));
        kv_row(out, "Sequence length", &bs.sequence_length);
        kv_row(out, "%GC", &format!("{:.2}", bs.percent_gc));
        kv_row(out, "Encoding", &bs.encoding);
        out.push_str("</tbody></table>\n");

        if !r.module_statuses.is_empty() {
            out.push_str("<h4>Modules</h4>\n<ul class=\"modules\">\n");
            for (mod_name, status) in &r.module_statuses {
                let class = match status {
                    ModuleStatus::Pass => "pass",
                    ModuleStatus::Warn => "warn",
                    ModuleStatus::Fail => "fail",
                };
                let label = match status {
                    ModuleStatus::Pass => "PASS",
                    ModuleStatus::Warn => "WARN",
                    ModuleStatus::Fail => "FAIL",
                };
                let _ = write!(
                    out,
                    "<li><span class=\"qc qc-{}\"><strong>{}</strong></span> {}</li>\n",
                    class,
                    label,
                    html_escape(mod_name)
                );
            }
            out.push_str("</ul>\n");
        }
        out.push_str("</details>\n");
    }
    out.push_str("</section>\n");
}

// ─── helpers ─────────────────────────────────────────────────────────────

fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

fn css_class(tool: &str) -> &'static str {
    match tool {
        "samtools" => "samtools",
        "bcftools" => "bcftools",
        "FastQC" => "fastqc",
        _ => "other",
    }
}

fn level_class(level: QcLevel) -> &'static str {
    match level {
        QcLevel::Pass => "qc-pass",
        QcLevel::Warn => "qc-warn",
        QcLevel::Fail => "qc-fail",
    }
}

fn td_opt_u64(out: &mut String, v: Option<u64>) {
    match v {
        Some(n) => {
            let _ = write!(out, "<td class=\"num\">{}</td>", format_number(n));
        }
        None => out.push_str("<td class=\"empty\">–</td>"),
    }
}

fn td_opt_u32(out: &mut String, v: Option<u32>) {
    match v {
        Some(n) => {
            let _ = write!(out, "<td class=\"num\">{}</td>", n);
        }
        None => out.push_str("<td class=\"empty\">–</td>"),
    }
}

fn td_opt_pct(out: &mut String, v: Option<f64>, classifier: impl Fn(f64) -> &'static str) {
    match v {
        Some(n) => {
            let _ = write!(out, "<td class=\"num qc {}\">{:.1}</td>", classifier(n), n);
        }
        None => out.push_str("<td class=\"empty\">–</td>"),
    }
}

fn td_opt_f64(
    out: &mut String,
    v: Option<f64>,
    decimals: usize,
    classifier: impl Fn(f64) -> &'static str,
) {
    match v {
        Some(n) => {
            let class = classifier(n);
            let css = if class.is_empty() {
                "num".to_string()
            } else {
                format!("num qc {}", class)
            };
            let _ = write!(out, "<td class=\"{}\">{:.*}</td>", css, decimals, n);
        }
        None => out.push_str("<td class=\"empty\">–</td>"),
    }
}

fn kv_row(out: &mut String, k: &str, v: &str) {
    let _ = write!(
        out,
        "<tr><th>{}</th><td>{}</td></tr>\n",
        html_escape(k),
        html_escape(v)
    );
}

fn kv_row_class(out: &mut String, k: &str, v: &str, class: &str) {
    let _ = write!(
        out,
        "<tr><th>{}</th><td class=\"qc {}\">{}</td></tr>\n",
        html_escape(k),
        class,
        html_escape(v)
    );
}

fn format_number(n: u64) -> String {
    let s = n.to_string();
    let mut result = String::new();
    for (i, c) in s.chars().rev().enumerate() {
        if i > 0 && i % 3 == 0 {
            result.push(',');
        }
        result.push(c);
    }
    result.chars().rev().collect()
}

fn file_basename(path: &Path) -> String {
    path.file_name()
        .map(|f| f.to_string_lossy().to_string())
        .unwrap_or_default()
}

const EMBEDDED_CSS: &str = r#"
:root {
  --bg: #ffffff;
  --fg: #1a1a1a;
  --muted: #6b7280;
  --border: #e5e7eb;
  --header-bg: #f8fafc;
  --code-bg: #f1f5f9;
  --pass: #16a34a;
  --warn: #d97706;
  --fail: #dc2626;
  --pass-bg: #dcfce7;
  --warn-bg: #fef3c7;
  --fail-bg: #fee2e2;
  --box-fill: #0891b2;
  --box-stroke: #155e75;
  --median-stroke: #ffffff;
  --whisker: #6b7280;
  --outlier: #d97706;
  --outlier-fail: #dc2626;
  --tool-samtools: #0891b2;
  --tool-bcftools: #c026d3;
  --tool-fastqc: #d97706;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #0f172a;
    --fg: #f1f5f9;
    --muted: #94a3b8;
    --border: #1e293b;
    --header-bg: #1e293b;
    --code-bg: #1e293b;
    --pass: #4ade80;
    --warn: #fbbf24;
    --fail: #f87171;
    --pass-bg: #14532d;
    --warn-bg: #713f12;
    --fail-bg: #7f1d1d;
    --box-fill: #0e7490;
    --box-stroke: #67e8f9;
    --median-stroke: #f8fafc;
    --tool-samtools: #22d3ee;
    --tool-bcftools: #e879f9;
    --tool-fastqc: #fbbf24;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
  background: var(--bg);
  color: var(--fg);
  line-height: 1.5;
}
header, section, footer {
  max-width: 1280px;
  margin: 0 auto;
  padding: 1.5rem 2rem;
}
header { border-bottom: 1px solid var(--border); }
header h1 { margin: 0 0 0.5rem 0; font-size: 1.75rem; letter-spacing: -0.02em; }
.meta { display: grid; grid-template-columns: max-content 1fr; gap: 0.25rem 1rem; margin: 0; font-size: 0.9rem; }
.meta dt { color: var(--muted); font-weight: 500; }
.meta dd { margin: 0; }
section { border-top: 1px solid var(--border); }
section h2 { margin: 0 0 1rem 0; font-size: 1.25rem; }
section h3 { margin: 1.25rem 0 0.5rem 0; font-size: 1rem; }
section h4 { margin: 0.75rem 0 0.25rem 0; font-size: 0.9rem; }
code {
  background: var(--code-bg);
  padding: 0.1rem 0.35rem;
  border-radius: 3px;
  font-family: ui-monospace, "SF Mono", Menlo, Consolas, monospace;
  font-size: 0.875em;
}
table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.875rem;
}
th, td {
  padding: 0.4rem 0.6rem;
  border-bottom: 1px solid var(--border);
  text-align: left;
}
thead th {
  background: var(--header-bg);
  font-weight: 600;
  font-size: 0.8rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--muted);
  position: sticky;
  top: 0;
}
.summary tbody tr:hover { background: var(--header-bg); }
td.num { text-align: right; font-variant-numeric: tabular-nums; }
td.empty { color: var(--muted); text-align: center; }
.tool { font-weight: 600; }
.tool-samtools { color: var(--tool-samtools); }
.tool-bcftools { color: var(--tool-bcftools); }
.tool-fastqc   { color: var(--tool-fastqc); }
.qc-pass { color: var(--pass); background: var(--pass-bg); }
.qc-warn { color: var(--warn); background: var(--warn-bg); }
.qc-fail { color: var(--fail); background: var(--fail-bg); }
.empty.good { color: var(--pass); }
.empty { color: var(--muted); font-style: italic; }
details {
  margin: 0.5rem 0;
  border: 1px solid var(--border);
  border-radius: 6px;
  background: var(--header-bg);
}
details summary {
  cursor: pointer;
  padding: 0.5rem 0.75rem;
  font-weight: 500;
  user-select: none;
}
details summary:hover { background: var(--code-bg); }
details > table, details > h4, details > ul { margin: 0.25rem 0.75rem 0.5rem 0.75rem; }
details > table { width: calc(100% - 1.5rem); }
table.detail th { font-weight: 500; color: var(--muted); width: 12rem; background: transparent; position: static; text-transform: none; letter-spacing: 0; font-size: 0.875rem; }
ul.modules { list-style: none; padding: 0; margin: 0.5rem 0; }
ul.modules li { padding: 0.2rem 0; font-size: 0.875rem; }
ul.modules .qc { padding: 0.05rem 0.4rem; border-radius: 3px; margin-right: 0.5rem; }
.boxplots { display: flex; flex-direction: column; gap: 1rem; }
.metric-group { padding: 0.5rem 0; }
.boxrow { display: flex; align-items: center; gap: 0.75rem; }
.glabel { font-size: 0.85rem; color: var(--muted); min-width: 8rem; font-family: ui-monospace, monospace; }
.boxplot { flex: 1; height: 50px; max-width: 800px; }
.boxrow.too-small .warn { color: var(--warn); font-size: 0.85rem; }
.axislabel { font-size: 11px; fill: var(--muted); font-family: ui-monospace, monospace; }
.whisker { stroke: var(--whisker); stroke-width: 1.5; }
.fence   { stroke: var(--whisker); stroke-width: 1.5; }
.box     { fill: var(--box-fill); stroke: var(--box-stroke); fill-opacity: 0.7; }
.median  { stroke: var(--median-stroke); stroke-width: 2.5; }
.outlier      { fill: var(--outlier); stroke: var(--outlier); }
.outlier-fail { fill: var(--outlier-fail); stroke: var(--outlier-fail); }
footer {
  border-top: 1px solid var(--border);
  color: var(--muted);
  font-size: 0.85rem;
  text-align: center;
  padding: 1rem 2rem;
}
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::types::{
        BcftoolsStats, BcftoolsSummary, FastqcBasicStats, FastqcReport, SamtoolsStats,
        SamtoolsSummary, TsTvStats,
    };
    use std::path::PathBuf;

    #[test]
    fn test_html_escape() {
        assert_eq!(html_escape("a<b>&\"c'd"), "a&lt;b&gt;&amp;&quot;c&#39;d");
        assert_eq!(html_escape("plain"), "plain");
    }

    fn results_with(samtools_count: usize) -> QcResults {
        let samtools: Vec<SamtoolsStats> = (0..samtools_count)
            .map(|i| SamtoolsStats {
                source_file: PathBuf::from(format!("/data/sample{}.stats", i)),
                summary: SamtoolsSummary {
                    raw_total_sequences: 1000,
                    reads_mapped: if i == 0 { 600 } else { 950 },
                    reads_duplicated: 50,
                    error_rate: 0.001,
                    average_quality: 30.0,
                    ..Default::default()
                },
                coverage_histogram: vec![],
                insert_size_histogram: vec![],
                read_length_histogram: vec![],
                gc_content_first: vec![],
                gc_content_last: vec![],
            })
            .collect();
        QcResults {
            scan_path: PathBuf::from("/test"),
            samtools_reports: samtools,
            bcftools_reports: vec![BcftoolsStats {
                source_file: PathBuf::from("/data/v.vcf.stats"),
                summary: BcftoolsSummary {
                    num_records: 100,
                    num_snps: 80,
                    num_indels: 20,
                    ..Default::default()
                },
                tstv: TsTvStats {
                    ts: 60,
                    tv: 30,
                    ts_tv_ratio: 2.0,
                    ..Default::default()
                },
                substitution_types: vec![],
                allele_freq: vec![],
                qual_dist: vec![],
                indel_dist: vec![],
                depth_dist: vec![],
            }],
            fastqc_reports: vec![FastqcReport {
                source_file: PathBuf::from("/data/s_fastqc.zip"),
                sample_name: "s".into(),
                basic_statistics: FastqcBasicStats {
                    total_sequences: 100,
                    percent_gc: 45.0,
                    ..Default::default()
                },
                per_base_quality: vec![],
                per_sequence_quality: vec![],
                per_base_gc_content: vec![],
                per_sequence_gc_content: vec![],
                sequence_length_dist: vec![],
                overrepresented_sequences: vec![],
                module_statuses: vec![],
            }],
        }
    }

    #[test]
    fn test_html_contains_sections() {
        let results = results_with(6);
        let thresholds = ThresholdConfig::default();
        let tmp = std::env::temp_dir().join("qcforge_test_html_sections.html");
        write_html(&tmp, &results, &thresholds, None, None).unwrap();
        let content = std::fs::read_to_string(&tmp).unwrap();
        assert!(content.contains("<title>QCForge report"));
        assert!(content.contains("id=\"summary\""));
        assert!(content.contains("id=\"cohort\""));
        assert!(content.contains("id=\"samtools\""));
        assert!(content.contains("id=\"bcftools\""));
        assert!(content.contains("id=\"fastqc\""));
        // sample0 has 60% mapping → should be flagged QC FAIL somewhere
        assert!(content.contains("qc-fail"));
        std::fs::remove_file(&tmp).ok();
    }

    #[test]
    fn test_html_contains_boxplot_svg() {
        let results = results_with(6);
        let thresholds = ThresholdConfig::default();
        let tmp = std::env::temp_dir().join("qcforge_test_html_svg.html");
        write_html(&tmp, &results, &thresholds, None, None).unwrap();
        let content = std::fs::read_to_string(&tmp).unwrap();
        assert!(content.contains("<svg"));
        assert!(content.contains("class=\"box\""));
        assert!(content.contains("class=\"median\""));
        std::fs::remove_file(&tmp).ok();
    }

    #[test]
    fn test_html_too_small_cohort() {
        // Only 3 samtools samples → all metrics too small for IQR.
        let results = results_with(3);
        let thresholds = ThresholdConfig::default();
        let tmp = std::env::temp_dir().join("qcforge_test_html_small.html");
        write_html(&tmp, &results, &thresholds, None, None).unwrap();
        let content = std::fs::read_to_string(&tmp).unwrap();
        assert!(content.contains("Cohort analysis requires"));
        // Summary section still renders
        assert!(content.contains("id=\"summary\""));
        std::fs::remove_file(&tmp).ok();
    }
}
